apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bry-fw2-front-end-service
  namespace: bry-fw2
  labels:
    app: {{ .Release.Name }}-bry-fw2-front-end
    family: {{ .Release.Name }}-bry-fw2
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-bry-fw2-front-end