apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1200m
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/(.+)/api/readiness {
          deny all;
      }
      location ~ ^/api/actuator/(prometheus) {
          deny all;
      }
  name: {{ .Release.Name }}-bry-fw2-ingress-front-end
  labels:
    app: {{ .Release.Name }}-bry-fw2
    family: {{ .Release.Name }}-bry-fw2
spec:
    rules:
    - host: "fw2.bry.tjmt.jus.br"
      http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-bry-fw2-front-end-service
                port:
                  number: 8080
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   name: {{ .Release.Name }}-bry-fw2-docs-ingress-front-end
#   labels:
#     app: {{ .Release.Name }}-bry-fw2
#     family: {{ .Release.Name }}-bry-fw2
# spec:
#   rules:
#   - host: api-assinatura.bry.com.br
#     http:
#       paths:
#       - backend:
#           serviceName: {{ .Release.Name }}-bry-fw2-docs-front-end-service
#           servicePort: 8080
#         path: /
#   tls:
#   - hosts:
#     - api-assinatura.bry.com.br
#     secretName: cert-gd-bry-com-br
